name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  env-dir:
    description: Environment directory
    required: true
  no-root:
    description: Do not install package in the environment
    required: false
    default: "false"
  args:
    description: Additional arguments to pass to the install command
    required: false

runs:
  using: "composite"
  steps:
    - name: Install poetry
      uses: ./.github/actions/setup-poetry

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
        cache-dependency-path: |
          ./poetry.lock
          ${{ inputs.env-dir }}/poetry.lock

    - run: |
        cd ${{ inputs.env-dir }}
        if [ "${{ inputs.no-root }}" = "true" ]; then
          poetry install --all-extras --no-root ${{ inputs.args }}
        else
          poetry install --all-extras ${{ inputs.args }}
        fi
      shell: bash
